### ISSUE TITLE
安装WindPT后页面一片空白

### ISSUE THREAD

**Issue by huxinmin** [labs7in0/WindPT#9]
Uncaught error with message 'E_WARNING: Invalid argument supplied for foreach()'

D:\APMServ5.2.6\www\htdocs\data\compile\template\torrent\extensions\torrent\template\admin\manage_run.tpl: 133

128: &lt;div class="cross"&gt;
129: &lt;ul id="J_ul_list_deniedfts" class="J_ul_list_public"&gt;
130: &lt;li&gt;
131: &lt;span class="span_3"&gt;后缀名(小写)&lt;/span&gt;
132: &lt;/li&gt;
133: &lt;?php foreach ($config['app.torrent.deniedfts'] as $deniedft) { ?&gt;
134: &lt;li&gt;
135: &lt;span class="span_3"&gt;&lt;input name="deniedfts[]" type="text" class="input length_2" value="&lt;?php echo htmlspecialchars($deniedft, ENT_QUOTES, 'UTF-8');?&gt;"&gt;&lt;/span&gt;
136: &lt;span class="span_4"&gt;&lt;a href="#" class="J_ul_list_remove"&gt;[删除]&lt;/a&gt;&lt;/span&gt;
137: &lt;/li&gt;
__Stack:

#12 D:\APMServ5.2.6\www\htdocs\wind\base\AbstractWindFrontController.php (245)
#11 D:\APMServ5.2.6\www\htdocs\data\compile\template\torrent\extensions\torrent\template\admin\manage_run.tpl (133) _errorHandle(2,"Invalid argument supplied for foreach()","D:\APMServ5.2.6\www\htdocs\data\compile\template\torrent\extensi…",133,array( '__tpl' => 'D:\\APMServ5.2.6\\www\\htdocs\\data\\compile/template/torrent/extensions/torrent/template/admin/manage_run.tpl', '__vars' => array 'loginUser' => NULL, 'config' => array( 'app.torrent.calcmd' => 'bc', 'app.torrent.calfunc' => 'exec', 'app.torrent.check' => array '0' => 'deniedfts', '1' => 'source', ), 'app.torrent.creditifopen' => '1', 'app.torrent.credits' => array( ), 'app.torrent.cron.peertimeout' => '15', 'app.torrent.cron.torrentimeout' => '0', 'app.torrent.showuserinfo' => array( '0' => 'threadside', '1' => 'profile', ), 'app.torrent.theme.showpeers' => array( '0' => 'index', '1' => 'forum_my', '2' => 'cate', '3' => 'widget', ), 'app.torrent.titlegen.douban' => '', 'app.torrent.titlegen.ifopen' => '1', 'app.torrent.torrentnameprefix' => 'phpwind 9.0', 'avatarUrl' => 'http://127.0.0.1/windid/attachment', 'cookie.domain' => '', 'cookie.path' => '', 'cookie.pre' => 'MIL', 'debug' => '1', 'hash' => 'llj2G41K', 'homeRouter' => array( 'm' => 'bbs', 'c' => 'index', 'a' => 'run', ), 'homeUrl' => 'index.php?m=bbs', 'info.mail' => 'admin@phpwind.com', 'info.name' => 'phpwind 9.0', 'info.notice' => '', 'info.url' => 'http://127.0.0.1', 'managereasons' => '问题已收集，谢谢反馈！ 建议已收集，谢谢反馈！ 已关注，谢谢反馈！ 广告帖 恶意灌水 非法内容 与版规不符 重复发帖 ------------------------------------------------ 优秀文章 原创内容', 'medal.isopen' => '1', 'onlinetime' => '30', 'punch.friend.open' => '1', 'punch.friend.reward' => array( 'friendNum' => '3', 'rewardMeNum' => '1', 'rewardNum' => '1', ), 'punch.open' => '1', 'punch.reward' => array( 'type' => '1', 'min' => '1', 'max' => '5', 'step' => '1', ), 'refreshtime' => '0', 'search.isopen' => '1', 'task.isOpen' => '1', 'theme.forum.default' => 'default', 'theme.forum.pack' => 'forum', 'theme.portal.pack' => 'portal/appcenter', 'theme.site.default' => 'pt', 'theme.site.pack' => 'site', 'theme.space.default' => 'default', 'theme.space.pack' => 'space', 'time.cv' => '0' 'time.timezone' => '8', 'upgradestrategy' => array( 'credit1' => '1', 'credit2' => '1', 'postnum' => '1', ), 'visit.message' => '站点升级中。。。', 'windid' => 'local', ), 'cronList' => array( 'ClearPeers' => array( ), 'ClearTorrents' => array( ), ), ), '__viewer' => NULL, 'loginUser' => NULL, 'config' => array( 'app.torrent.calcmd' => 'bc', 'app.torrent.calfunc' => 'exec', 'app.torrent.check' => array( '0' => 'deniedfts', '1' => 'source', ), 'app.torrent.creditifopen' => '1', 'app.torrent.credits' => array( ), 'app.torrent.cron.peertimeout' => '15', 'app.torrent.cron.torrentimeout' => '0', 'app.torrent.showuserinfo' => array( '0' => 'threadside', '1' => 'profile', ), 'app.torrent.theme.showpeers' => array( '0' => 'index', '1' => 'forum_my', '2' => 'cate', '3' => 'widget', ), 'app.torrent.titlegen.douban' => '', 'app.torrent.titlegen.ifopen' => '1', 'app.torrent.torrentnameprefix' => 'phpwind 9.0', 'avatarUrl' => 'http://127.0.0.1/windid/attachment', 'cookie.domain' => '', 'cookie.path' => '', 'cookie.pre' => 'MIL', 'debug' => '1', 'hash' => 'llj2G41K', 'homeRouter' => array( 'm' => 'bbs', 'c' => 'index' 'a' => 'run', ), 'homeUrl' => 'index.php?m=bbs', 'info.mail' => 'admin@phpwind.com', 'info.name' => 'phpwind 9.0', 'info.notice' => '', 'info.url' => 'http://127.0.0.1', 'managereasons' => '问题已收集，谢谢反馈！ 建议已收集，谢谢反馈！ 已关注，谢谢反馈！ 广告帖 恶意灌水 非法内容 与版规不符 重复发帖 ------------------------------------------------ 优秀文章 原创内容', 'medal.isopen' => '1', 'onlinetime' => '30', 'punch.friend.open' => '1', 'punch.friend.reward' => array( 'friendNum' => '3', 'rewardMeNum' => '1', 'rewardNum' => '1', ), 'punch.open' => '1', 'punch.reward' => array( 'type' => '1', 'min' => '1', 'max' => '5', 'step' => '1', ), 'refreshtime' => '0', 'search.isopen' => '1', 'task.isOpen' => '1', 'theme.forum.default' => 'default', 'theme.forum.pack' => 'forum', 'theme.portal.pack' => 'portal/appcenter', 'theme.site.default' => 'pt', 'theme.site.pack' => 'site', 'theme.space.default' => 'default', 'theme.space.pack' => 'space', 'time.cv' => '0', 'time.timezone' => '8' 'upgradestrategy' => array( 'credit1' => '1', 'credit2' => '1', 'postnum' => '1', ), 'visit.message' => '站点升级中。。。', 'windid' => 'local', ), 'cronList' => array( 'ClearPeers' => array( ), 'ClearTorrents' => array( ), ), ))
#10 D:\APMServ5.2.6\www\htdocs\wind\viewer\IWindViewerResolver.php (59) include("D:\APMServ5.2.6\www\htdocs\data\compile\template\torrent\extensi…")
#09 D:\APMServ5.2.6\www\htdocs\wind\viewer\resolver\WindViewerResolver.php (38) render("D:\APMServ5.2.6\www\htdocs\data\compile/template/torrent/extensi…",array( 'loginUser' => NULL, 'config' => array( 'app.torrent.calcmd' => 'bc', 'app.torrent.calfunc' => 'exec', 'app.torrent.check' => array( '0' => 'deniedfts', '1' => 'source', ), 'app.torrent.creditifopen' => '1', 'app.torrent.credits' => array( ), 'app.torrent.cron.peertimeout' => '15', 'app.torrent.cron.torrentimeout' => '0', 'app.torrent.showuserinfo' => array( '0' => 'threadside', '1' => 'profile', ), 'app.torrent.theme.showpeers' => array( '0' => 'index', '1' => 'forum_my', '2' => 'cate', '3' => 'widget', ), 'app.torrent.titlegen.douban' => '', 'app.torrent.titlegen.ifopen' => '1', 'app.torrent.torrentnameprefix' => 'phpwind 9.0', 'avatarUrl' => 'http://127.0.0.1/windid/attachment', 'cookie.domain' => '', 'cookie.path' => '', 'cookie.pre' => 'MIL', 'debug' => '1', 'hash' => 'llj2G41K', 'homeRouter' => array( 'm' => 'bbs', 'c' => 'index', 'a' => 'run', ), 'homeUrl' => 'index.php?m=bbs', 'info.mail' => 'admin@phpwind.com', 'info.name' => 'phpwind 9.0', 'info.notice' => '', 'info.url' => 'http://127.0.0.1', 'managereasons' => '问题已收集，谢谢反馈！ 建议已收集，谢谢反馈！ 已关注，谢谢反馈！ 广告帖 恶意灌水 非法内容 与版规不符 重复发帖 ------------------------------------------------ 优秀文章 原创内容', 'medal.isopen' => '1', 'onlinetime' => '30', 'punch.friend.open' => '1', 'punch.friend.reward' => array( 'friendNum' => '3', 'rewardMeNum' => '1', 'rewardNum' => '1', ), 'punch.open' => '1', 'punch.reward' => array( 'type' => '1', 'min' => '1', 'max' => '5', 'step' => '1', ), 'refreshtime' => '0', 'search.isopen' => '1', 'task.isOpen' => '1', 'theme.forum.default' => 'default', 'theme.forum.pack' => 'forum', 'theme.portal.pack' => 'portal/appcenter', 'theme.site.default' => 'pt', 'theme.site.pack' => 'site', 'theme.space.default' => 'default', 'theme.space.pack' => 'space', 'time.cv' => '0' 'time.timezone' => '8', 'upgradestrategy' => array( 'credit1' => '1', 'credit2' => '1', 'postnum' => '1', ), 'visit.message' => '站点升级中。。。', 'windid' => 'local', ), 'cronList' => array( 'ClearPeers' => array( ), 'ClearTorrents' => array( ), ), ),WindViewerResolver)
#08 D:\APMServ5.2.6\www\htdocs\wind\viewer\WindView.php (145) windFetch()
#07 D:\APMServ5.2.6\www\htdocs\wind\web\WindDispatcher.php (43) render(false)
#06 D:\APMServ5.2.6\www\htdocs\wind\web\WindWebApplication.php (26) dispatch(WindForward,WindRouter,false)
#05 D:\APMServ5.2.6\www\htdocs\wind\base\AbstractWindApplication.php (91) doDispatch(WindForward)
#04 D:\APMServ5.2.6\www\htdocs\wind\base\AbstractWindFrontController.php (205) run(WindRouter)
#03 D:\APMServ5.2.6\www\htdocs\wind\web\WindWebFrontController.php (20) run()
#02 D:\APMServ5.2.6\www\htdocs\src\wekit.php (38) run()
#01 D:\APMServ5.2.6\www\htdocs\admin.php (7) run("pwadmin",array( 'router' => array( 'config' => array( 'module' => array( 'default-value' => 'default', ), 'routes' => array( 'admin' => array( 'class' => 'LIB:route.PwAdminRoute', 'default' => true, ), ), ), ), ))
The server encountered an internal error and failed to process your request. Please try again later. If this error is temporary, reloading the page might resolve the problem. 
If you are able to contact the administrator report this error message.(http://www.windframework.com/)

**Comment by kinosang** [comment]
try 9d3a8e1

**Comment by kinosang** [comment]
PHPWind not support PHP 5.2, upgrade to PHP 5.4 or later.
